version: '3'
services:
  p2p:
    image: <IMAGE_NAME>
    ports:
      - 7667
    environment:
      - SERVICENAME=<IMAGE_NAME>_p2p
      - NUMNODES=<NUM_NODES>
      - PYTHONUNBUFFERED=1
    networks:
      - web
networks:
  web:
    driver: bridge
